export const POST_ANSWER_SHEET_REQUEST = 'POST_ANSWER_SHEET_REQUEST';
export const POST_ANSWER_SHEET_SUCCESS = 'POST_ANSWER_SHEET_SUCCESS';
export const POST_ANSWER_SHEET_FAILURE = 'POST_ANSWER_SHEET_FAILURE';
export const POST_ANSWER_SHEET = 'POST_ANSWER_SHEET';
