export const POST_CLASSIFIER_FORM = 'POST_CLASSIFIER_FORM';
export const POST_CLASSIFIER_FORM_REQUEST = 'POST_CLASSIFIER_FORM_REQUEST';
export const POST_CLASSIFIER_FORM_SUCCESS = 'POST_CLASSIFIER_FORM_SUCCESS';
export const POST_CLASSIFIER_FORM_FAILURE = 'POST_CLASSIFIER_FORM_FAILURE';
