export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE';

export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE';

export const POST_COURSE_REQUEST = 'POST_COURSE_REQUEST';
export const POST_COURSE_SUCCESS = 'POST_COURSE_SUCCESS';
export const POST_COURSE_FAILURE = 'POST_COURSE_FAILURE';
export const POST_COURSE = 'POST_COURSE';
